name: Release to GH Releases
on: push

permissions:
  contents: write

jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
     
      - name: Get version
        run: echo "tag_name=$(node -e "console.info(require('./chr2img/src/package.json').version)")" >> $GITHUB_ENV
      - name: Show Version
        run: "echo Releasing version ${{ env.tag_name }}"

      - name: Check version tag
        id: releaseExists
        uses: mukunku/tag-exists-action@v1.2.0
        with: 
          tag: ${{ env.tag_name }}
      - name: Fail if tag already exists
        if: ${{ steps.releaseExists.outputs.exists == true }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('This version has already been published')


      - name: Build
        run: "sh build.sh"

      - name: Release All
        uses: softprops/action-gh-release@v1
        with: 
          tag_name: ${{ env.tag_name }}
          files: |
            bin/windows-x64.zip
            bin/linux-x64.tar.gz
            bin/linux-arm64.tar.gz
            README.md
